
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox panelContent;

	private global::Gtk.ComboBox listPosts;

	private global::Gtk.Button btnConsultar;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.DefaultWidth = 800;
		this.DefaultHeight = 600;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.panelContent = new global::Gtk.VBox();
		this.panelContent.Name = "panelContent";
		this.panelContent.Spacing = 6;
		// Container child panelContent.Gtk.Box+BoxChild
		this.listPosts = global::Gtk.ComboBox.NewText();
		this.listPosts.Name = "listPosts";
		this.panelContent.Add(this.listPosts);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.panelContent[this.listPosts]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child panelContent.Gtk.Box+BoxChild
		this.btnConsultar = new global::Gtk.Button();
		this.btnConsultar.CanFocus = true;
		this.btnConsultar.Name = "btnConsultar";
		this.btnConsultar.UseUnderline = true;
		this.btnConsultar.Label = global::Mono.Unix.Catalog.GetString("Consultar");
		this.panelContent.Add(this.btnConsultar);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.panelContent[this.btnConsultar]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		this.Add(this.panelContent);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.btnConsultar.Clicked += new global::System.EventHandler(this.OnBtnConsultarClicked);
	}
}
